/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GfaWebItemsItemDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "creationTime", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(rename = "creatorId", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<String>,
    #[serde(rename = "lastModificationTime", skip_serializing_if = "Option::is_none")]
    pub last_modification_time: Option<String>,
    #[serde(rename = "lastModifierId", skip_serializing_if = "Option::is_none")]
    pub last_modifier_id: Option<String>,
    #[serde(rename = "sourceId", skip_serializing_if = "Option::is_none")]
    pub source_id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "buyPrice", skip_serializing_if = "Option::is_none")]
    pub buy_price: Option<f64>,
    #[serde(rename = "sellPrice", skip_serializing_if = "Option::is_none")]
    pub sell_price: Option<f64>,
    #[serde(rename = "profitLoss", skip_serializing_if = "Option::is_none")]
    pub profit_loss: Option<f64>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "remaining", skip_serializing_if = "Option::is_none")]
    pub remaining: Option<f64>,
    #[serde(rename = "salePurchaseId", skip_serializing_if = "Option::is_none")]
    pub sale_purchase_id: Option<String>,
}

impl GfaWebItemsItemDto {
    pub fn new() -> GfaWebItemsItemDto {
        GfaWebItemsItemDto {
            id: None,
            creation_time: None,
            creator_id: None,
            last_modification_time: None,
            last_modifier_id: None,
            source_id: None,
            name: None,
            code: None,
            buy_price: None,
            sell_price: None,
            profit_loss: None,
            quantity: None,
            date: None,
            remaining: None,
            sale_purchase_id: None,
        }
    }
}


