/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GfaWebPurchasesCreateUpdatePurchaseDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "creationTime", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(rename = "creatorId", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<String>,
    #[serde(rename = "lastModificationTime", skip_serializing_if = "Option::is_none")]
    pub last_modification_time: Option<String>,
    #[serde(rename = "lastModifierId", skip_serializing_if = "Option::is_none")]
    pub last_modifier_id: Option<String>,
    #[serde(rename = "sourceId", skip_serializing_if = "Option::is_none")]
    pub source_id: Option<i32>,
    #[serde(rename = "datePurchase", skip_serializing_if = "Option::is_none")]
    pub date_purchase: Option<String>,
    #[serde(rename = "vendorId", skip_serializing_if = "Option::is_none")]
    pub vendor_id: Option<String>,
    #[serde(rename = "vendorSourceId", skip_serializing_if = "Option::is_none")]
    pub vendor_source_id: Option<i32>,
    #[serde(rename = "totalAmount", skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<f64>,
}

impl GfaWebPurchasesCreateUpdatePurchaseDto {
    pub fn new() -> GfaWebPurchasesCreateUpdatePurchaseDto {
        GfaWebPurchasesCreateUpdatePurchaseDto {
            id: None,
            creation_time: None,
            creator_id: None,
            last_modification_time: None,
            last_modifier_id: None,
            source_id: None,
            date_purchase: None,
            vendor_id: None,
            vendor_source_id: None,
            total_amount: None,
        }
    }
}


