/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GfaWebPurchasesPurchaseGroup {
    #[serde(rename = "0")]
    _0,
    #[serde(rename = "1")]
    _1,

}

impl ToString for GfaWebPurchasesPurchaseGroup {
    fn to_string(&self) -> String {
        match self {
            Self::_0 => String::from("0"),
            Self::_1 => String::from("1"),
        }
    }
}

impl Default for GfaWebPurchasesPurchaseGroup {
    fn default() -> GfaWebPurchasesPurchaseGroup {
        Self::_0
    }
}




