/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpModelingReturnValueApiDescriptionModel {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "typeSimple", skip_serializing_if = "Option::is_none")]
    pub type_simple: Option<String>,
}

impl VoloAbpHttpModelingReturnValueApiDescriptionModel {
    pub fn new() -> VoloAbpHttpModelingReturnValueApiDescriptionModel {
        VoloAbpHttpModelingReturnValueApiDescriptionModel {
            _type: None,
            type_simple: None,
        }
    }
}


