/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpRemoteServiceValidationErrorInfo {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<String>>,
}

impl VoloAbpHttpRemoteServiceValidationErrorInfo {
    pub fn new() -> VoloAbpHttpRemoteServiceValidationErrorInfo {
        VoloAbpHttpRemoteServiceValidationErrorInfo {
            message: None,
            members: None,
        }
    }
}


