/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpPermissionManagementUpdatePermissionsDto {
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<crate::models::VoloAbpPermissionManagementUpdatePermissionDto>>,
}

impl VoloAbpPermissionManagementUpdatePermissionsDto {
    pub fn new() -> VoloAbpPermissionManagementUpdatePermissionsDto {
        VoloAbpPermissionManagementUpdatePermissionsDto {
            permissions: None,
        }
    }
}


