/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo {
    #[serde(rename = "userNameOrEmailAddress")]
    pub user_name_or_email_address: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "rememberMe", skip_serializing_if = "Option::is_none")]
    pub remember_me: Option<bool>,
}

impl VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo {
    pub fn new(user_name_or_email_address: String, password: String) -> VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo {
        VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo {
            user_name_or_email_address,
            password,
            remember_me: None,
        }
    }
}


