/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpIdentityIdentityRoleDto {
    #[serde(rename = "extraProperties", skip_serializing_if = "Option::is_none")]
    pub extra_properties: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isDefault", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    #[serde(rename = "isStatic", skip_serializing_if = "Option::is_none")]
    pub is_static: Option<bool>,
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "concurrencyStamp", skip_serializing_if = "Option::is_none")]
    pub concurrency_stamp: Option<String>,
}

impl VoloAbpIdentityIdentityRoleDto {
    pub fn new() -> VoloAbpIdentityIdentityRoleDto {
        VoloAbpIdentityIdentityRoleDto {
            extra_properties: None,
            id: None,
            name: None,
            is_default: None,
            is_static: None,
            is_public: None,
            concurrency_stamp: None,
        }
    }
}


