/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto {
    #[serde(rename = "isEnabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
}

impl VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto {
    pub fn new() -> VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto {
        VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto {
            is_enabled: None,
        }
    }
}


