/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpModelingModuleApiDescriptionModel {
    #[serde(rename = "rootPath", skip_serializing_if = "Option::is_none")]
    pub root_path: Option<String>,
    #[serde(rename = "remoteServiceName", skip_serializing_if = "Option::is_none")]
    pub remote_service_name: Option<String>,
    #[serde(rename = "controllers", skip_serializing_if = "Option::is_none")]
    pub controllers: Option<::std::collections::HashMap<String, crate::models::VoloAbpHttpModelingControllerApiDescriptionModel>>,
}

impl VoloAbpHttpModelingModuleApiDescriptionModel {
    pub fn new() -> VoloAbpHttpModelingModuleApiDescriptionModel {
        VoloAbpHttpModelingModuleApiDescriptionModel {
            root_path: None,
            remote_service_name: None,
            controllers: None,
        }
    }
}


