/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAccountSendPasswordResetCodeDto {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "appName")]
    pub app_name: String,
    #[serde(rename = "returnUrl", skip_serializing_if = "Option::is_none")]
    pub return_url: Option<String>,
    #[serde(rename = "returnUrlHash", skip_serializing_if = "Option::is_none")]
    pub return_url_hash: Option<String>,
}

impl VoloAbpAccountSendPasswordResetCodeDto {
    pub fn new(email: String, app_name: String) -> VoloAbpAccountSendPasswordResetCodeDto {
        VoloAbpAccountSendPasswordResetCodeDto {
            email,
            app_name,
            return_url: None,
            return_url_hash: None,
        }
    }
}


