/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpModelingControllerApiDescriptionModel {
    #[serde(rename = "controllerName", skip_serializing_if = "Option::is_none")]
    pub controller_name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "interfaces", skip_serializing_if = "Option::is_none")]
    pub interfaces: Option<Vec<crate::models::VoloAbpHttpModelingControllerInterfaceApiDescriptionModel>>,
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<::std::collections::HashMap<String, crate::models::VoloAbpHttpModelingActionApiDescriptionModel>>,
}

impl VoloAbpHttpModelingControllerApiDescriptionModel {
    pub fn new() -> VoloAbpHttpModelingControllerApiDescriptionModel {
        VoloAbpHttpModelingControllerApiDescriptionModel {
            controller_name: None,
            _type: None,
            interfaces: None,
            actions: None,
        }
    }
}


