/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto {
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<::std::collections::HashMap<String, crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto>>,
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto {
            properties: None,
            configuration: None,
        }
    }
}


