/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpPermissionManagementProviderInfoDto {
    #[serde(rename = "providerName", skip_serializing_if = "Option::is_none")]
    pub provider_name: Option<String>,
    #[serde(rename = "providerKey", skip_serializing_if = "Option::is_none")]
    pub provider_key: Option<String>,
}

impl VoloAbpPermissionManagementProviderInfoDto {
    pub fn new() -> VoloAbpPermissionManagementProviderInfoDto {
        VoloAbpPermissionManagementProviderInfoDto {
            provider_name: None,
            provider_key: None,
        }
    }
}


