/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto {
    #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto {
            time_zone: None,
        }
    }
}


