/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto {
    #[serde(rename = "isAuthenticated", skip_serializing_if = "Option::is_none")]
    pub is_authenticated: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    #[serde(rename = "impersonatorUserId", skip_serializing_if = "Option::is_none")]
    pub impersonator_user_id: Option<String>,
    #[serde(rename = "impersonatorTenantId", skip_serializing_if = "Option::is_none")]
    pub impersonator_tenant_id: Option<String>,
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "surName", skip_serializing_if = "Option::is_none")]
    pub sur_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "emailVerified", skip_serializing_if = "Option::is_none")]
    pub email_verified: Option<bool>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "phoneNumberVerified", skip_serializing_if = "Option::is_none")]
    pub phone_number_verified: Option<bool>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<String>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto {
            is_authenticated: None,
            id: None,
            tenant_id: None,
            impersonator_user_id: None,
            impersonator_tenant_id: None,
            user_name: None,
            name: None,
            sur_name: None,
            email: None,
            email_verified: None,
            phone_number: None,
            phone_number_verified: None,
            roles: None,
        }
    }
}


