/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto {
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto {
            kind: None,
        }
    }
}


