/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone {
    #[serde(rename = "iana", skip_serializing_if = "Option::is_none")]
    pub iana: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone>>,
    #[serde(rename = "windows", skip_serializing_if = "Option::is_none")]
    pub windows: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone {
        VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone {
            iana: None,
            windows: None,
        }
    }
}


