/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpModelingActionApiDescriptionModel {
    #[serde(rename = "uniqueName", skip_serializing_if = "Option::is_none")]
    pub unique_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "httpMethod", skip_serializing_if = "Option::is_none")]
    pub http_method: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "supportedVersions", skip_serializing_if = "Option::is_none")]
    pub supported_versions: Option<Vec<String>>,
    #[serde(rename = "parametersOnMethod", skip_serializing_if = "Option::is_none")]
    pub parameters_on_method: Option<Vec<crate::models::VoloAbpHttpModelingMethodParameterApiDescriptionModel>>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<crate::models::VoloAbpHttpModelingParameterApiDescriptionModel>>,
    #[serde(rename = "returnValue", skip_serializing_if = "Option::is_none")]
    pub return_value: Option<Box<crate::models::VoloAbpHttpModelingReturnValueApiDescriptionModel>>,
    #[serde(rename = "allowAnonymous", skip_serializing_if = "Option::is_none")]
    pub allow_anonymous: Option<bool>,
}

impl VoloAbpHttpModelingActionApiDescriptionModel {
    pub fn new() -> VoloAbpHttpModelingActionApiDescriptionModel {
        VoloAbpHttpModelingActionApiDescriptionModel {
            unique_name: None,
            name: None,
            http_method: None,
            url: None,
            supported_versions: None,
            parameters_on_method: None,
            parameters: None,
            return_value: None,
            allow_anonymous: None,
        }
    }
}


