/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpModelingPropertyApiDescriptionModel {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "jsonName", skip_serializing_if = "Option::is_none")]
    pub json_name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "typeSimple", skip_serializing_if = "Option::is_none")]
    pub type_simple: Option<String>,
    #[serde(rename = "isRequired", skip_serializing_if = "Option::is_none")]
    pub is_required: Option<bool>,
}

impl VoloAbpHttpModelingPropertyApiDescriptionModel {
    pub fn new() -> VoloAbpHttpModelingPropertyApiDescriptionModel {
        VoloAbpHttpModelingPropertyApiDescriptionModel {
            name: None,
            json_name: None,
            _type: None,
            type_simple: None,
            is_required: None,
        }
    }
}


