/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpRemoteServiceErrorInfo {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "validationErrors", skip_serializing_if = "Option::is_none")]
    pub validation_errors: Option<Vec<crate::models::VoloAbpHttpRemoteServiceValidationErrorInfo>>,
}

impl VoloAbpHttpRemoteServiceErrorInfo {
    pub fn new() -> VoloAbpHttpRemoteServiceErrorInfo {
        VoloAbpHttpRemoteServiceErrorInfo {
            code: None,
            message: None,
            details: None,
            data: None,
            validation_errors: None,
        }
    }
}


