/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpSettingManagementUpdateEmailSettingsDto {
    #[serde(rename = "smtpHost", skip_serializing_if = "Option::is_none")]
    pub smtp_host: Option<String>,
    #[serde(rename = "smtpPort", skip_serializing_if = "Option::is_none")]
    pub smtp_port: Option<i32>,
    #[serde(rename = "smtpUserName", skip_serializing_if = "Option::is_none")]
    pub smtp_user_name: Option<String>,
    #[serde(rename = "smtpPassword", skip_serializing_if = "Option::is_none")]
    pub smtp_password: Option<String>,
    #[serde(rename = "smtpDomain", skip_serializing_if = "Option::is_none")]
    pub smtp_domain: Option<String>,
    #[serde(rename = "smtpEnableSsl", skip_serializing_if = "Option::is_none")]
    pub smtp_enable_ssl: Option<bool>,
    #[serde(rename = "smtpUseDefaultCredentials", skip_serializing_if = "Option::is_none")]
    pub smtp_use_default_credentials: Option<bool>,
    #[serde(rename = "defaultFromAddress")]
    pub default_from_address: String,
    #[serde(rename = "defaultFromDisplayName")]
    pub default_from_display_name: String,
}

impl VoloAbpSettingManagementUpdateEmailSettingsDto {
    pub fn new(default_from_address: String, default_from_display_name: String) -> VoloAbpSettingManagementUpdateEmailSettingsDto {
        VoloAbpSettingManagementUpdateEmailSettingsDto {
            smtp_host: None,
            smtp_port: None,
            smtp_user_name: None,
            smtp_password: None,
            smtp_domain: None,
            smtp_enable_ssl: None,
            smtp_use_default_credentials: None,
            default_from_address,
            default_from_display_name,
        }
    }
}


