/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto {
    #[serde(rename = "entities", skip_serializing_if = "Option::is_none")]
    pub entities: Option<::std::collections::HashMap<String, crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto>>,
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto {
            entities: None,
            configuration: None,
        }
    }
}


