/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isAvailable", skip_serializing_if = "Option::is_none")]
    pub is_available: Option<bool>,
}

impl VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto {
    pub fn new() -> VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto {
        VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto {
            id: None,
            name: None,
            is_available: None,
        }
    }
}


