/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpIdentityIdentityRoleUpdateDto {
    #[serde(rename = "extraProperties", skip_serializing_if = "Option::is_none")]
    pub extra_properties: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "isDefault", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "concurrencyStamp", skip_serializing_if = "Option::is_none")]
    pub concurrency_stamp: Option<String>,
}

impl VoloAbpIdentityIdentityRoleUpdateDto {
    pub fn new(name: String) -> VoloAbpIdentityIdentityRoleUpdateDto {
        VoloAbpIdentityIdentityRoleUpdateDto {
            extra_properties: None,
            name,
            is_default: None,
            is_public: None,
            concurrency_stamp: None,
        }
    }
}


