/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAccountRegisterDto {
    #[serde(rename = "extraProperties", skip_serializing_if = "Option::is_none")]
    pub extra_properties: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "emailAddress")]
    pub email_address: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "appName")]
    pub app_name: String,
}

impl VoloAbpAccountRegisterDto {
    pub fn new(user_name: String, email_address: String, password: String, app_name: String) -> VoloAbpAccountRegisterDto {
        VoloAbpAccountRegisterDto {
            extra_properties: None,
            user_name,
            email_address,
            password,
            app_name,
        }
    }
}


