/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpPermissionManagementPermissionGroupDto {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<crate::models::VoloAbpPermissionManagementPermissionGrantInfoDto>>,
}

impl VoloAbpPermissionManagementPermissionGroupDto {
    pub fn new() -> VoloAbpPermissionManagementPermissionGroupDto {
        VoloAbpPermissionManagementPermissionGroupDto {
            name: None,
            display_name: None,
            permissions: None,
        }
    }
}


