/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto {
    #[serde(rename = "modules", skip_serializing_if = "Option::is_none")]
    pub modules: Option<::std::collections::HashMap<String, crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto>>,
    #[serde(rename = "enums", skip_serializing_if = "Option::is_none")]
    pub enums: Option<::std::collections::HashMap<String, crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumDto>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto {
            modules: None,
            enums: None,
        }
    }
}


