/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone {
    #[serde(rename = "timeZoneId", skip_serializing_if = "Option::is_none")]
    pub time_zone_id: Option<String>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone {
        VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone {
            time_zone_id: None,
        }
    }
}


