/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiDto {
    #[serde(rename = "onTable", skip_serializing_if = "Option::is_none")]
    pub on_table: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiTableDto>>,
    #[serde(rename = "onCreateForm", skip_serializing_if = "Option::is_none")]
    pub on_create_form: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiFormDto>>,
    #[serde(rename = "onEditForm", skip_serializing_if = "Option::is_none")]
    pub on_edit_form: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiFormDto>>,
    #[serde(rename = "lookup", skip_serializing_if = "Option::is_none")]
    pub lookup: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiLookupDto>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiDto {
            on_table: None,
            on_create_form: None,
            on_edit_form: None,
            lookup: None,
        }
    }
}


