/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpRemoteServiceErrorResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::VoloAbpHttpRemoteServiceErrorInfo>>,
}

impl VoloAbpHttpRemoteServiceErrorResponse {
    pub fn new() -> VoloAbpHttpRemoteServiceErrorResponse {
        VoloAbpHttpRemoteServiceErrorResponse {
            error: None,
        }
    }
}


