/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpIdentityIdentityUserUpdateDto {
    #[serde(rename = "extraProperties", skip_serializing_if = "Option::is_none")]
    pub extra_properties: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "surname", skip_serializing_if = "Option::is_none")]
    pub surname: Option<String>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "lockoutEnabled", skip_serializing_if = "Option::is_none")]
    pub lockout_enabled: Option<bool>,
    #[serde(rename = "roleNames", skip_serializing_if = "Option::is_none")]
    pub role_names: Option<Vec<String>>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "concurrencyStamp", skip_serializing_if = "Option::is_none")]
    pub concurrency_stamp: Option<String>,
}

impl VoloAbpIdentityIdentityUserUpdateDto {
    pub fn new(user_name: String, email: String) -> VoloAbpIdentityIdentityUserUpdateDto {
        VoloAbpIdentityIdentityUserUpdateDto {
            extra_properties: None,
            user_name,
            name: None,
            surname: None,
            email,
            phone_number: None,
            lockout_enabled: None,
            role_names: None,
            password: None,
            concurrency_stamp: None,
        }
    }
}


