/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto {
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<::std::collections::HashMap<String, bool>>,
    #[serde(rename = "grantedPolicies", skip_serializing_if = "Option::is_none")]
    pub granted_policies: Option<::std::collections::HashMap<String, bool>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto {
            policies: None,
            granted_policies: None,
        }
    }
}


