/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpIdentityIdentityUserDto {
    #[serde(rename = "extraProperties", skip_serializing_if = "Option::is_none")]
    pub extra_properties: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "creationTime", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(rename = "creatorId", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<String>,
    #[serde(rename = "lastModificationTime", skip_serializing_if = "Option::is_none")]
    pub last_modification_time: Option<String>,
    #[serde(rename = "lastModifierId", skip_serializing_if = "Option::is_none")]
    pub last_modifier_id: Option<String>,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    #[serde(rename = "deleterId", skip_serializing_if = "Option::is_none")]
    pub deleter_id: Option<String>,
    #[serde(rename = "deletionTime", skip_serializing_if = "Option::is_none")]
    pub deletion_time: Option<String>,
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "surname", skip_serializing_if = "Option::is_none")]
    pub surname: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "emailConfirmed", skip_serializing_if = "Option::is_none")]
    pub email_confirmed: Option<bool>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "phoneNumberConfirmed", skip_serializing_if = "Option::is_none")]
    pub phone_number_confirmed: Option<bool>,
    #[serde(rename = "lockoutEnabled", skip_serializing_if = "Option::is_none")]
    pub lockout_enabled: Option<bool>,
    #[serde(rename = "lockoutEnd", skip_serializing_if = "Option::is_none")]
    pub lockout_end: Option<String>,
    #[serde(rename = "concurrencyStamp", skip_serializing_if = "Option::is_none")]
    pub concurrency_stamp: Option<String>,
}

impl VoloAbpIdentityIdentityUserDto {
    pub fn new() -> VoloAbpIdentityIdentityUserDto {
        VoloAbpIdentityIdentityUserDto {
            extra_properties: None,
            id: None,
            creation_time: None,
            creator_id: None,
            last_modification_time: None,
            last_modifier_id: None,
            is_deleted: None,
            deleter_id: None,
            deletion_time: None,
            tenant_id: None,
            user_name: None,
            name: None,
            surname: None,
            email: None,
            email_confirmed: None,
            phone_number: None,
            phone_number_confirmed: None,
            lockout_enabled: None,
            lockout_end: None,
            concurrency_stamp: None,
        }
    }
}


