/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpModelingTypeApiDescriptionModel {
    #[serde(rename = "baseType", skip_serializing_if = "Option::is_none")]
    pub base_type: Option<String>,
    #[serde(rename = "isEnum", skip_serializing_if = "Option::is_none")]
    pub is_enum: Option<bool>,
    #[serde(rename = "enumNames", skip_serializing_if = "Option::is_none")]
    pub enum_names: Option<Vec<String>>,
    #[serde(rename = "enumValues", skip_serializing_if = "Option::is_none")]
    pub enum_values: Option<Vec<serde_json::Value>>,
    #[serde(rename = "genericArguments", skip_serializing_if = "Option::is_none")]
    pub generic_arguments: Option<Vec<String>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<crate::models::VoloAbpHttpModelingPropertyApiDescriptionModel>>,
}

impl VoloAbpHttpModelingTypeApiDescriptionModel {
    pub fn new() -> VoloAbpHttpModelingTypeApiDescriptionModel {
        VoloAbpHttpModelingTypeApiDescriptionModel {
            base_type: None,
            is_enum: None,
            enum_names: None,
            enum_values: None,
            generic_arguments: None,
            properties: None,
        }
    }
}


