/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpHttpModelingMethodParameterApiDescriptionModel {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "typeAsString", skip_serializing_if = "Option::is_none")]
    pub type_as_string: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "typeSimple", skip_serializing_if = "Option::is_none")]
    pub type_simple: Option<String>,
    #[serde(rename = "isOptional", skip_serializing_if = "Option::is_none")]
    pub is_optional: Option<bool>,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<serde_json::Value>,
}

impl VoloAbpHttpModelingMethodParameterApiDescriptionModel {
    pub fn new() -> VoloAbpHttpModelingMethodParameterApiDescriptionModel {
        VoloAbpHttpModelingMethodParameterApiDescriptionModel {
            name: None,
            type_as_string: None,
            _type: None,
            type_simple: None,
            is_optional: None,
            default_value: None,
        }
    }
}


