/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpIdentityChangePasswordInput {
    #[serde(rename = "currentPassword", skip_serializing_if = "Option::is_none")]
    pub current_password: Option<String>,
    #[serde(rename = "newPassword")]
    pub new_password: String,
}

impl VoloAbpIdentityChangePasswordInput {
    pub fn new(new_password: String) -> VoloAbpIdentityChangePasswordInput {
        VoloAbpIdentityChangePasswordInput {
            current_password: None,
            new_password,
        }
    }
}


