/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAccountResetPasswordDto {
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "resetToken")]
    pub reset_token: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl VoloAbpAccountResetPasswordDto {
    pub fn new(reset_token: String, password: String) -> VoloAbpAccountResetPasswordDto {
        VoloAbpAccountResetPasswordDto {
            user_id: None,
            reset_token,
            password,
        }
    }
}


