/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationConfigurationDto {
    #[serde(rename = "localization", skip_serializing_if = "Option::is_none")]
    pub localization: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDto>>,
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto>>,
    #[serde(rename = "setting", skip_serializing_if = "Option::is_none")]
    pub setting: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDto>>,
    #[serde(rename = "currentUser", skip_serializing_if = "Option::is_none")]
    pub current_user: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto>>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDto>>,
    #[serde(rename = "multiTenancy", skip_serializing_if = "Option::is_none")]
    pub multi_tenancy: Option<Box<crate::models::VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto>>,
    #[serde(rename = "currentTenant", skip_serializing_if = "Option::is_none")]
    pub current_tenant: Option<Box<crate::models::VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto>>,
    #[serde(rename = "timing", skip_serializing_if = "Option::is_none")]
    pub timing: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto>>,
    #[serde(rename = "clock", skip_serializing_if = "Option::is_none")]
    pub clock: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto>>,
    #[serde(rename = "objectExtensions", skip_serializing_if = "Option::is_none")]
    pub object_extensions: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationConfigurationDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationConfigurationDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationConfigurationDto {
            localization: None,
            auth: None,
            setting: None,
            current_user: None,
            features: None,
            multi_tenancy: None,
            current_tenant: None,
            timing: None,
            clock: None,
            object_extensions: None,
        }
    }
}


