/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiLookupDto {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "resultListPropertyName", skip_serializing_if = "Option::is_none")]
    pub result_list_property_name: Option<String>,
    #[serde(rename = "displayPropertyName", skip_serializing_if = "Option::is_none")]
    pub display_property_name: Option<String>,
    #[serde(rename = "valuePropertyName", skip_serializing_if = "Option::is_none")]
    pub value_property_name: Option<String>,
    #[serde(rename = "filterParamName", skip_serializing_if = "Option::is_none")]
    pub filter_param_name: Option<String>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiLookupDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiLookupDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiLookupDto {
            url: None,
            result_list_property_name: None,
            display_property_name: None,
            value_property_name: None,
            filter_param_name: None,
        }
    }
}


