/*
 * gfa_web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto {
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "englishName", skip_serializing_if = "Option::is_none")]
    pub english_name: Option<String>,
    #[serde(rename = "threeLetterIsoLanguageName", skip_serializing_if = "Option::is_none")]
    pub three_letter_iso_language_name: Option<String>,
    #[serde(rename = "twoLetterIsoLanguageName", skip_serializing_if = "Option::is_none")]
    pub two_letter_iso_language_name: Option<String>,
    #[serde(rename = "isRightToLeft", skip_serializing_if = "Option::is_none")]
    pub is_right_to_left: Option<bool>,
    #[serde(rename = "cultureName", skip_serializing_if = "Option::is_none")]
    pub culture_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nativeName", skip_serializing_if = "Option::is_none")]
    pub native_name: Option<String>,
    #[serde(rename = "dateTimeFormat", skip_serializing_if = "Option::is_none")]
    pub date_time_format: Option<Box<crate::models::VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto>>,
}

impl VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto {
    pub fn new() -> VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto {
        VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto {
            display_name: None,
            english_name: None,
            three_letter_iso_language_name: None,
            two_letter_iso_language_name: None,
            is_right_to_left: None,
            culture_name: None,
            name: None,
            native_name: None,
            date_time_format: None,
        }
    }
}


