using System.Collections.Generic;

namespace gfa_worker_common
{
    public class BaseItem
    {
        public List<Record> Records { get; set; }
        public int TotalRecords { get; set; }
        public int LastRec { get; set; }
    }

    public class Record
    {
        public int ID { get; set; }
        public int Jenis { get; set; }
        public string Kode { get; set; }
        public string KodeC2 { get; set; }
        public string KodeC3 { get; set; }
        public string KodeC4 { get; set; }
        public string KodeC5 { get; set; }
        public string Kode2 { get; set; }
        public int GrpStkID { get; set; }
        public string GroupStk { get; set; }
        public int GrpSt2ID { get; set; }
        public string GroupSt2 { get; set; }
        public int GrpSt3ID { get; set; }
        public string GroupSt3 { get; set; }
        public string Nama { get; set; }
        public string NamaEx1 { get; set; }
        public string NamaEx2 { get; set; }
        public string ExtInfo1 { get; set; }
        public string ExtInfo2 { get; set; }
        public string ExtInfo3 { get; set; }
        public int MUHargaBeli { get; set; }
        public int MUHargaJual1 { get; set; }
        public int MUHargaJual2 { get; set; }
        public int MUHargaJual3 { get; set; }
        public int MUHargaJual4 { get; set; }
        public int MUHargaJual5 { get; set; }
        public int MUHargaMin { get; set; }
        public string HargaBeli { get; set; }
        public double HargaBeliNilai { get; set; }
        public double HargaBeliEx1Nilai { get; set; }
        public double HargaBeliEx2Nilai { get; set; }
        public string HargaJual1 { get; set; }
        public double HargaJual1Nilai { get; set; }
        public double HargaJual1Ex1Nilai { get; set; }
        public double HargaJual1Ex2Nilai { get; set; }
        public string HargaJual2 { get; set; }
        public double HargaJual2Nilai { get; set; }
        public double HargaJual2Ex1Nilai { get; set; }
        public double HargaJual2Ex2Nilai { get; set; }
        public string HargaJual3 { get; set; }
        public double HargaJual3Nilai { get; set; }
        public double HargaJual3Ex1Nilai { get; set; }
        public double HargaJual3Ex2Nilai { get; set; }
        public string HargaJual4 { get; set; }
        public double HargaJual4Nilai { get; set; }
        public double HargaJual4Ex1Nilai { get; set; }
        public double HargaJual4Ex2Nilai { get; set; }
        public string HargaJual5 { get; set; }
        public double HargaJual5Nilai { get; set; }
        public double HargaJual5Ex1Nilai { get; set; }
        public double HargaJual5Ex2Nilai { get; set; }
        public string HargaMin { get; set; }
        public double HargaMinNilai { get; set; }
        public double HargaMinEx1Nilai { get; set; }
        public double HargaMinEx2Nilai { get; set; }
        public double HargaBeliPer { get; set; }
        public double DiscBeliPer { get; set; }
        public double HargaMinPer { get; set; }
        public double HargaJual1Per { get; set; }
        public double HargaJual2Per { get; set; }
        public double HargaJual3Per { get; set; }
        public double HargaJual4Per { get; set; }
        public double HargaJual5Per { get; set; }
        public int HargaBeliSat { get; set; }
        public int HargaMinSat { get; set; }
        public int HargaJual1Sat { get; set; }
        public int HargaJual2Sat { get; set; }
        public int HargaJual3Sat { get; set; }
        public int HargaJual4Sat { get; set; }
        public int HargaJual5Sat { get; set; }
        public double DiscJual1Per1 { get; set; }
        public double DiscJual1Per2 { get; set; }
        public double DiscJual1Per3 { get; set; }
        public double DiscJual2Per1 { get; set; }
        public double DiscJual2Per2 { get; set; }
        public double DiscJual2Per3 { get; set; }
        public double DiscJual3Per1 { get; set; }
        public double DiscJual3Per2 { get; set; }
        public double DiscJual3Per3 { get; set; }
        public double DiscJual4Per1 { get; set; }
        public double DiscJual4Per2 { get; set; }
        public double DiscJual4Per3 { get; set; }
        public double DiscJual5Per1 { get; set; }
        public double DiscJual5Per2 { get; set; }
        public double DiscJual5Per3 { get; set; }
        public int VendorID { get; set; }
        public string Vendor { get; set; }
        public int DefaultSatuan { get; set; }
        public int SatuanEceran { get; set; }
        public double MinJualJumlah { get; set; }
        public int MinJualSatuan { get; set; }
        public string Sat_01 { get; set; }
        public string Sat_02 { get; set; }
        public string Sat_03 { get; set; }
        public string Sat_04 { get; set; }
        public string Sat_05 { get; set; }
        public string Sat_06 { get; set; }
        public string Sat_07 { get; set; }
        public string Sat_08 { get; set; }
        public string Sat_09 { get; set; }
        public string Sat_10 { get; set; }
        public double Sat_K_01 { get; set; }
        public double Sat_K_02 { get; set; }
        public double Sat_K_03 { get; set; }
        public double Sat_K_04 { get; set; }
        public double Sat_K_05 { get; set; }
        public double Sat_K_06 { get; set; }
        public double Sat_K_07 { get; set; }
        public double Sat_K_08 { get; set; }
        public double Sat_K_09 { get; set; }
        public double Sat_K_10 { get; set; }
        public string Catatan { get; set; }
        public string Picture { get; set; }
        public int PictureExist { get; set; }
        public int Gudang_01 { get; set; }
        public int Gudang_02 { get; set; }
        public int Gudang_03 { get; set; }
        public int Gudang_04 { get; set; }
        public int Gudang_05 { get; set; }
        public int Gudang_06 { get; set; }
        public int Gudang_07 { get; set; }
        public int Gudang_08 { get; set; }
        public int Gudang_09 { get; set; }
        public int Gudang_10 { get; set; }
        public int Gudang_11 { get; set; }
        public int Gudang_12 { get; set; }
        public int Gudang_13 { get; set; }
        public int Gudang_14 { get; set; }
        public int Gudang_15 { get; set; }
        public int Gudang_16 { get; set; }
        public int Gudang_17 { get; set; }
        public int Gudang_18 { get; set; }
        public int Gudang_19 { get; set; }
        public int Gudang_20 { get; set; }
        public int Gudang_21 { get; set; }
        public int Gudang_22 { get; set; }
        public int Gudang_23 { get; set; }
        public int Gudang_24 { get; set; }
        public int Gudang_25 { get; set; }
        public int Gudang_26 { get; set; }
        public int Gudang_27 { get; set; }
        public int Gudang_28 { get; set; }
        public int Gudang_29 { get; set; }
        public int Gudang_30 { get; set; }
        public int Tnp_Harga { get; set; }
        public int Non_Pajak { get; set; }
        public int Flx_Harga { get; set; }
        public int Tnp_DisGlb { get; set; }
        public int Tnp_Adj01 { get; set; }
        public int Tnp_Adj02 { get; set; }
        public int Tnp_Adj03 { get; set; }
        public int Tnp_Adj04 { get; set; }
        public int Tnp_Adj05 { get; set; }
        public int Tnp_Charge { get; set; }
        public int Blh_BwhHbl { get; set; }
        public int Tnp_SpsDsc { get; set; }
        public int Non_Bonus { get; set; }
        public int NotAvailable { get; set; }
        public int TO_InputHarga { get; set; }
        public string SubInfo1 { get; set; }
        public string SubInfo2 { get; set; }
        public string SubInfo3 { get; set; }
        public string SubInfo4 { get; set; }
    }

    
}