#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Root {
    #[serde(rename = "Records")]
    pub records: Vec<Record>,
    #[serde(rename = "TotalRecords")]
    pub total_records: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Record {
    #[serde(rename = "ID")]
    pub id: i64,
    #[serde(rename = "SALORD_ID")]
    pub salord_id: i64,
    #[serde(rename = "ECRLST_ID")]
    pub ecrlst_id: i64,
    #[serde(rename = "RESERV_ID")]
    pub reserv_id: i64,
    #[serde(rename = "DIVISI_ID")]
    pub divisi_id: i64,
    #[serde(rename = "JENPEN_ID")]
    pub jenpen_id: i64,
    #[serde(rename = "PERKIR_1")]
    pub perkir_1: i64,
    #[serde(rename = "PERKIR_2")]
    pub perkir_2: i64,
    #[serde(rename = "RECORD_CAT")]
    pub record_cat: String,
    #[serde(rename = "BARANG_KLR")]
    pub barang_klr: i64,
    #[serde(rename = "LINKED")]
    pub linked: i64,
    #[serde(rename = "NO_MILIK")]
    pub no_milik: i64,
    #[serde(rename = "NO_MLK_CSH")]
    pub no_mlk_csh: i64,
    #[serde(rename = "NO")]
    pub no: i64,
    #[serde(rename = "NO_C")]
    pub no_c: String,
    #[serde(rename = "NO_PJK_SR")]
    pub no_pjk_sr: i64,
    #[serde(rename = "NO_PJK_PRE")]
    pub no_pjk_pre: i64,
    #[serde(rename = "NO_PJK")]
    pub no_pjk: i64,
    #[serde(rename = "PO")]
    pub po: String,
    #[serde(rename = "GUDANG")]
    pub gudang: i64,
    #[serde(rename = "TANGGAL")]
    pub tanggal: String,
    #[serde(rename = "TGL_PAJAK")]
    pub tgl_pajak: String,
    #[serde(rename = "PUKUL")]
    pub pukul: i64,
    #[serde(rename = "PELANG")]
    pub pelang: i64,
    #[serde(rename = "PELEXT_ID")]
    pub pelext_id: i64,
    #[serde(rename = "PEL_NAMA")]
    pub pel_nama: String,
    #[serde(rename = "PEL_ALAMAT")]
    pub pel_alamat: String,
    #[serde(rename = "MAUANG")]
    pub mauang: i64,
    #[serde(rename = "KURS")]
    pub kurs: f64,
    #[serde(rename = "KURS_PAJAK")]
    pub kurs_pajak: f64,
    #[serde(rename = "TOT_HARGA")]
    pub tot_harga: f64,
    #[serde(rename = "TOT_HAREX1")]
    pub tot_harex1: f64,
    #[serde(rename = "TOT_HAREX2")]
    pub tot_harex2: f64,
    #[serde(rename = "TOT_DISC")]
    pub tot_disc: f64,
    #[serde(rename = "TOT_PAJAK")]
    pub tot_pajak: f64,
    #[serde(rename = "TOT_RETUR")]
    pub tot_retur: f64,
    #[serde(rename = "DISC_NILAI")]
    pub disc_nilai: f64,
    #[serde(rename = "DISC_PERST")]
    pub disc_perst: f64,
    #[serde(rename = "PPN_TIPE")]
    pub ppn_tipe: i64,
    #[serde(rename = "PPN_PERS")]
    pub ppn_pers: f64,
    #[serde(rename = "PPN_NILAI")]
    pub ppn_nilai: f64,
    #[serde(rename = "ADJ_01")]
    pub adj_01: f64,
    #[serde(rename = "ADJ_02")]
    pub adj_02: f64,
    #[serde(rename = "ADJ_03")]
    pub adj_03: f64,
    #[serde(rename = "ADJ_04")]
    pub adj_04: f64,
    #[serde(rename = "ADJ_05")]
    pub adj_05: f64,
    #[serde(rename = "DEPOSIT")]
    pub deposit: f64,
    #[serde(rename = "TGL_LUNAS")]
    pub tgl_lunas: String,
    #[serde(rename = "LUNAS")]
    pub lunas: f64,
    #[serde(rename = "LUN_TIPE_1")]
    pub lun_tipe_1: i64,
    #[serde(rename = "LUN_DOC_1")]
    pub lun_doc_1: String,
    #[serde(rename = "LUN_DOC_1A")]
    pub lun_doc_1a: String,
    #[serde(rename = "LUNAS_1")]
    pub lunas_1: f64,
    #[serde(rename = "CHARGES_1")]
    pub charges_1: f64,
    #[serde(rename = "TERM_CRD")]
    pub term_crd: i64,
    #[serde(rename = "SALES")]
    pub sales: i64,
    #[serde(rename = "SALES_KOM")]
    pub sales_kom: f64,
    #[serde(rename = "SUPIR")]
    pub supir: i64,
    #[serde(rename = "CATATAN")]
    pub catatan: String,
    #[serde(rename = "CATATAN_2")]
    pub catatan_2: String,
    #[serde(rename = "CATATAN_3")]
    pub catatan_3: String,
    #[serde(rename = "SALDO_AWAL")]
    pub saldo_awal: i64,
    #[serde(rename = "ALS_BATAL")]
    pub als_batal: String,
    #[serde(rename = "CLEAR_AR")]
    pub clear_ar: String,
    #[serde(rename = "CETAK_OLEH")]
    pub cetak_oleh: i64,
    #[serde(rename = "CETAK_TGL")]
    pub cetak_tgl: String,
    #[serde(rename = "CETAK_JAM")]
    pub cetak_jam: String,
    #[serde(rename = "CETA2_OLEH")]
    pub ceta2_oleh: i64,
    #[serde(rename = "CETA2_TGL")]
    pub ceta2_tgl: String,
    #[serde(rename = "CETA2_JAM")]
    pub ceta2_jam: String,
    #[serde(rename = "KONF_OLEH")]
    pub konf_oleh: i64,
    #[serde(rename = "KONF_TGL")]
    pub konf_tgl: String,
    #[serde(rename = "KONF_JAM")]
    pub konf_jam: String,
    #[serde(rename = "IMP_OWNID")]
    pub imp_ownid: i64,
    #[serde(rename = "IMP_ID")]
    pub imp_id: i64,
    #[serde(rename = "IMP_OLEH")]
    pub imp_oleh: i64,
    #[serde(rename = "IMP_TGL")]
    pub imp_tgl: String,
    #[serde(rename = "IMP_JAM")]
    pub imp_jam: String,
    #[serde(rename = "EXP_OLEH")]
    pub exp_oleh: i64,
    #[serde(rename = "EXP_TGL")]
    pub exp_tgl: String,
    #[serde(rename = "EXP_JAM")]
    pub exp_jam: String,
    #[serde(rename = "INPUT_OLEH")]
    pub input_oleh: i64,
    #[serde(rename = "UBAH_OLEH")]
    pub ubah_oleh: i64,
    #[serde(rename = "HAPUS_OLEH")]
    pub hapus_oleh: i64,
    #[serde(rename = "KUNCI_OLEH")]
    pub kunci_oleh: i64,
    #[serde(rename = "TGL_INPUT")]
    pub tgl_input: String,
    #[serde(rename = "TGL_UBAH")]
    pub tgl_ubah: String,
    #[serde(rename = "TGL_HAPUS")]
    pub tgl_hapus: String,
    #[serde(rename = "TGL_KUNCI")]
    pub tgl_kunci: String,
    #[serde(rename = "JAM_INPUT")]
    pub jam_input: String,
    #[serde(rename = "JAM_UBAH")]
    pub jam_ubah: String,
    #[serde(rename = "JAM_HAPUS")]
    pub jam_hapus: String,
    #[serde(rename = "JAM_KUNCI")]
    pub jam_kunci: String,
    #[serde(rename = "DBF_VLD")]
    pub dbf_vld: String,
    #[serde(rename = "DivisiText")]
    pub divisi_text: String,
    #[serde(rename = "GudangText")]
    pub gudang_text: String,
    #[serde(rename = "SalesNama")]
    pub sales_nama: String,
    #[serde(rename = "SalesTelepon")]
    pub sales_telepon: String,
    #[serde(rename = "SalesNonAktif")]
    pub sales_non_aktif: String,
    #[serde(rename = "PelangganKode")]
    pub pelanggan_kode: String,
    #[serde(rename = "PelangganNama")]
    pub pelanggan_nama: String,
    #[serde(rename = "PelangganDaerah")]
    pub pelanggan_daerah: String,
    #[serde(rename = "PelangganGroup")]
    pub pelanggan_group: String,
    #[serde(rename = "PelangganGroup2")]
    pub pelanggan_group2: String,
    #[serde(rename = "Detail")]
    pub detail: Vec<Detail>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Detail {
    #[serde(rename = "PENJUA_ID")]
    pub penjua_id: i64,
    #[serde(rename = "PEMBEL_ID")]
    pub pembel_id: i64,
    #[serde(rename = "STKTRA_ID")]
    pub stktra_id: i64,
    #[serde(rename = "PERKIR_ID")]
    pub perkir_id: i64,
    #[serde(rename = "STOCK_ID")]
    pub stock_id: i64,
    #[serde(rename = "STOCK_ID2")]
    pub stock_id2: i64,
    #[serde(rename = "STOCK_GDG")]
    pub stock_gdg: i64,
    #[serde(rename = "STOCK_NON")]
    pub stock_non: String,
    #[serde(rename = "STKSER_ID")]
    pub stkser_id: i64,
    #[serde(rename = "STKSER_1")]
    pub stkser_1: String,
    #[serde(rename = "STKSER_2")]
    pub stkser_2: String,
    #[serde(rename = "PELANG")]
    pub pelang: i64,
    #[serde(rename = "SALES")]
    pub sales: i64,
    #[serde(rename = "TANGGAL")]
    pub tanggal: String,
    #[serde(rename = "SATUAN")]
    pub satuan: i64,
    #[serde(rename = "SATUAN_C")]
    pub satuan_c: String,
    #[serde(rename = "JUMLAH")]
    pub jumlah: f64,
    #[serde(rename = "OUT_SATUAN")]
    pub out_satuan: i64,
    #[serde(rename = "OUT_JUMLAH")]
    pub out_jumlah: f64,
    #[serde(rename = "BON_SATUAN")]
    pub bon_satuan: i64,
    #[serde(rename = "BON_JUMLAH")]
    pub bon_jumlah: f64,
    #[serde(rename = "HARGA")]
    pub harga: f64,
    #[serde(rename = "HARGA_EX1")]
    pub harga_ex1: f64,
    #[serde(rename = "HARGA_EX2")]
    pub harga_ex2: f64,
    #[serde(rename = "DISC_PERS")]
    pub disc_pers: f64,
    #[serde(rename = "DISC_PERS2")]
    pub disc_pers2: f64,
    #[serde(rename = "DISC_PERS3")]
    pub disc_pers3: f64,
    #[serde(rename = "DISC_NILAI")]
    pub disc_nilai: f64,
    #[serde(rename = "PPN_PERS")]
    pub ppn_pers: f64,
    #[serde(rename = "PPN_NILAI")]
    pub ppn_nilai: f64,
    #[serde(rename = "MAST_DISC")]
    pub mast_disc: f64,
    #[serde(rename = "MAST_PPN")]
    pub mast_ppn: f64,
    #[serde(rename = "MAST_ADJ_1")]
    pub mast_adj_1: f64,
    #[serde(rename = "MAST_ADJ_2")]
    pub mast_adj_2: f64,
    #[serde(rename = "MAST_ADJ_3")]
    pub mast_adj_3: f64,
    #[serde(rename = "MAST_ADJ_4")]
    pub mast_adj_4: f64,
    #[serde(rename = "MAST_ADJ_5")]
    pub mast_adj_5: f64,
    #[serde(rename = "HPP")]
    pub hpp: f64,
    #[serde(rename = "HPP_BONUS")]
    pub hpp_bonus: f64,
    #[serde(rename = "ALS_BATAL")]
    pub als_batal: String,
    #[serde(rename = "EXPIRED")]
    pub expired: String,
    #[serde(rename = "CATATAN")]
    pub catatan: String,
    #[serde(rename = "TGL_HAPUS")]
    pub tgl_hapus: String,
    #[serde(rename = "DBF_VLD")]
    pub dbf_vld: String,
    #[serde(rename = "DiscPers1Nilai")]
    pub disc_pers1nilai: i64,
    #[serde(rename = "DiscPers2Nilai")]
    pub disc_pers2nilai: i64,
    #[serde(rename = "DiscPers3Nilai")]
    pub disc_pers3nilai: i64,
    #[serde(rename = "DiscPersNilai")]
    pub disc_pers_nilai: i64,
    #[serde(rename = "ItemGrpStk")]
    pub item_grp_stk: i64,
    #[serde(rename = "ItemGrpSt2")]
    pub item_grp_st2: i64,
    #[serde(rename = "ItemGrpSt3")]
    pub item_grp_st3: i64,
    #[serde(rename = "ItemKode")]
    pub item_kode: String,
    #[serde(rename = "ItemKode2")]
    pub item_kode2: String,
    #[serde(rename = "ItemNama")]
    pub item_nama: String,
    #[serde(rename = "ItemJumlah")]
    pub item_jumlah: String,
    #[serde(rename = "ItemSatuan")]
    pub item_satuan: String,
    #[serde(rename = "ItemBonusJml")]
    pub item_bonus_jml: String,
    #[serde(rename = "ItemBonusSat")]
    pub item_bonus_sat: String,
}
