# Stage 1
FROM node:12-alpine as build
RUN mkdir -p /app
WORKDIR /app

COPY package.json /app

RUN npm install

COPY [".", "/app"]
COPY ["environments/environment_prod.ts", "/app/src/environments/environment.ts"]
COPY ["environments/environment_prod.ts", "/app/src/environments/environment.prod.ts"]
RUN npm run build --prod


# # Stage 2

FROM nginx:1.17.1-alpine

COPY --from=build /app/dist/gfa_web /usr/share/nginx/html

