name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -c Release "web\aspnet-core\src\gfa_web.DbMigrator" -o ".\dist\Migrator" -r "linux-x64" /p:PublishSingleFile=true
    - name: Run Migration
      run: cp "web\aspnet-core\appsettings\mi_appsettings_prod.json" ".\dist\Migrator\appsettings.json"
    - name: Test
      run: cat ".\dist\Migrator\appsettings.json"
