# This is a basic workflow to help you get started with Actions

name: worker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
          
      - name: Build Worker
        run: |
             cd worker
             dotnet publish -c Release "gfa-worker-item" -o ".\dist\item" -r "win-x86"
             dotnet publish -c Release "gfa-worker-purchase" -o ".\dist\purchase" -r "win-x86" 
             dotnet publish -c Release "gfa-worker-vendor" -o ".\dist\vendor" -r "win-x86" 
             dotnet publish -c Release "gfa-worker-sales" -o ".\dist\sales" -r "win-x86" 
             
             zip  ./dist/worker.zip ./dist/item/* ./dist/purchase/* ./dist/vendor/* ./dist/sales/*
             
             rm -rf dist/item
             rm -rf dist/purchase
             rm -rf dist/vendor
             rm -rf dist/sales
             
             ls
             
             
             
